name: CategoriesForHomalg
version: 2014.05.08
date: 12/12/2013
description: TODO

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

GAP: ">= 4.6"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2014.06.26"
      url: "http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/AutoDoc"
    - name: "ToolsForHomalg"
      version: ">= 2014.05.08"
      url: "http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/ToolsForHomalg"

www: http://www.TODO.INSERT.WEBPAGE.HERE/
readme: http://www.TODO.INSERT.WEBPAGE.HERE/README
packageinfo: http://www.TODO.INSERT.WEBPAGE.HERE/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.TODO.INSERT.WEBPAGE.HERE/CategoriesForHomalg-2014.05.08.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
